### ISSUE TITLE
build.sh does not make a working app

### ISSUE THREAD

**Issue by ThetaGamma** [Wowu/microsoft-todo-osx#4]
I tried to rebuild the To-Do App with an actual nativefier 7.6.8, node.js 11.1.0, electron v3.0.3 under OSX HighSierra with the command mentioned in `build.sh` with no success.

**Symptoms:**
- starting the app from scratch opens a regular chrome window which redirects me to Microsoft Authentication, "to-Do" opens in the normal "chrome" browser
- App shows constantly the running cogs from Microsoft webpage

**My solution:** 
changing the nativefier command to process authentication within the app
`
nativefier --name "To-Do" -p "OSX" --counter -i ./To-Do --single-instance --width=880 --height=630 --min-width=600 --min-height=330 --internal-urls=".*?\.[microsoftonline|live]\.*?" --disable-context-menu --inject ./style.css https://todo.microsoft.com/login
`
I extended the Regex to include private and enterprise login.

Remark: your "compiled" version from github works as aspected!

**Comment by wowu** [comment]
Thanks for the issue! I extended your regex to also include the app url.
