### ISSUE TITLE
Official app ready for pre-order in Mac App Store

### ISSUE THREAD

**Issue by mariozaizar** [Wowu/microsoft-todo-osx#6]
> Heads up that the Mac app is just around the corner! Head to the Mac App Store and click “Pre-order” to be one of the first to download it for free. msft.social/qcgFN4

https://apps.apple.com/app/microsoft-to-do/id1274495053?mt=12&utm_source=Direct

<img width="1792" alt="Screen Shot 2019-06-13 at 12 48 24 PM" src="https://user-images.githubusercontent.com/164819/59462907-8e84d380-8dd9-11e9-820e-d31924629604.png">

**Comment by sdrahan** [comment]
Dear Karol, thank you a lot for your effort on creating and maintaining this wrapper. Your unofficial app served me perfectly well until Microsoft released the native app.
Have a nice day!

**Comment by wowu** [comment]
I've added some info about the official app to the project readme, I'm glad you liked the app, thanks 😊
